### ISSUE TITLE
errors generated 

### ISSUE THREAD

**Issue by bliu100** [lavenderca/TSScall#8]
I am doing a test run for TSScall as follow:
python TSScall.py  GSE43390_40HT_f.bedgraph GSE43390_40HT_r.bedgraph mm9.chrom.sizes GSE43390_40HT_m37.bed

An error message was generated:
Traceback (most recent call last):
  File "TSScall.py", line 987, in <module>
    TSSCalling(**vars(args))
  File "TSScall.py", line 142, in __init__
    assert os.path.exists(self.forward_bedgraph)
AssertionError

GSE43390 data was downloaded from GEO database according to the reference GENES & DEVELOPMENT 32:26–41. Could you help? Thanks

**Comment by lavenderca** [comment]
The AssertionError implies that the path for the forward bedGraph does not exist.  Can you verify that the paths to the input files are accurate?
